spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

my:
  personalised:
    variable: "je suis sur le profile par default"